SUBROUTINE SUB(A, B, D)
USE TYPE_MODEL         , ONLY : MODEL
#include "arp_shallow_mf.intfb.h"
IMPLICIT NONE 

TYPE(MODEL), INTENT(INOUT) :: YDMODEL

REAL (KIND=JPRB) :: D(: ,:)
REAL (KIND=JPRB), INTENT(INOUT) :: A(KLON, KLEV)
REAL (KIND=JPRB), POINTER, INTENT(INOUT) :: A(KLON, KLEV)

REAL (KIND=JPRB), INTENT(INOUT) :: B(: ,:)

REAL (KIND=JPRB), INTENT(OUT) :: PECT(KLON, KLEV) 

!REAL (KIND=JPRB), POINTER :: ZR(KLON)
REAL (KIND=JPRB), ALLOCATABLE :: ZA(KLON)

REAL (KIND=JPRB) :: Z(KLON, KLEV) !allowed
REAL (KIND=JPRB) :: ZPROF (KLEV) !forbidden
REAL (KIND=JPRB) :: ZZ (4,2:5) !allowed 

REAL(KIND=JPRB), POINTER :: ZR(:,:)
REAL(KIND=JPRB), TARGET :: ZR0(KLON,KFLEVG)
IF (PRESENT (PR)) THEN
ZR => PR
ELSE
ZR => ZR0
ENDIF

IF (PRESENT (PR)) THEN
ZR => PR
ENDIF


CALL ARP_SHALLOW_MF (A)
CALL TOTO (A)

A(:) = 0.0

END SUBROUTINE
