SUBROUTINE SUB(YDML_DYN, A, B, D, YDML_DYN)
USE FIELD_ACCESS_MODULE

USE TYPE_MODEL         , ONLY : MODEL
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK

USE MY_MODULE, ONLY : MY_VAR
USE MY_MODULE, ONLY : MY_VAR_TYPE
USE MY_MODULE, ONLY : TMY_VAR
USE MY_MODULE, ONLY : MTYTYPE_VAR
#include "arp_shallow_mf.intfb.h"
IMPLICIT NONE 

TYPE(MODEL), INTENT(INOUT) :: YDMODEL
TYPE(MODEL), INTENT(INOUT) :: YDVARS
TYPE(MODEL) :: D

TYPE (DYN), INTENT(IN) :: YDML_DYN
REAL (KIND=JPRB), INTENT(INOUT) :: A(KLON, KLEV)
REAL (KIND=JPRB), POINTER, INTENT(INOUT) :: A(KLON, KLEV)

REAL (KIND=JPRB), INTENT(INOUT) :: B(: ,:)

REAL (KIND=JPRB), INTENT(OUT) :: PECT(KLON, KLEV) 
REAL (KIND=JPRB), INTENT(INOUT) :: PLSCAW(KLON, KLEV, XX)

!REAL (KIND=JPRB), POINTER :: ZR(KLON)
REAL (KIND=JPRB), ALLOCATABLE :: ZA(KLON)


REAL (KIND=JPRB) :: Z1(KLON) 
REAL (KIND=JPRB) :: Z2(KLON)

REAL (KIND=JPRB) :: C(KKLON, KLEV) !allowed

REAL (KIND=JPRB) :: Z(KLON, KLEV) !allowed
REAL (KIND=JPRB) :: ZPROF (KLEV) !forbidden
REAL (KIND=JPRB) :: ZZ (4,2:5) !allowed 

REAL(KIND=JPRB), POINTER :: ZR(:,:)
REAL(KIND=JPRB), TARGET :: ZR0(KLON,KFLEVG)

REAL (KIND=JPRB) :: ZSURF(KLON)
REAL (KIND=JPRB) :: ZSUM
REAL (KIND=JPRB) :: ZMIN
REAL (KIND=JPRB) :: ZMAX
INTEGER :: ISORT (KIT_)
INTEGER :: JI_
LOGICAL ::GTRIG1_(KIT_)
LOGICAL ::GTRIG2_(KIT_)
REAL :: GTRIG1(KLON)
INTEGER            ,INTENT(IN)   :: KIT_

IF (PRESENT (PR)) THEN
ZR => PR
ELSE
ZR => ZR0
ENDIF

IF (PRESENT (PR)) THEN
ZR => PR
ENDIF


CALL ARP_SHALLOW_MF (A)
CALL TOTO (A)
!CALL LAITRI_WENO(YDDYN,NPROMA,PLSCAW(0,1,YDML_DYN%YYTLSCAW%M_WDLAT), YDML_DYN%ZTAB(1, :))
!CALL LAITRI_WENO(YDDYN,NPROMA,PLSCAW(1,1,YDML_DYN%YYTLSCAW%M_WDLAT), YDML_DYN%ZTAB2(1, 2))

CALL LAITRI_WENO(YDDYN,NPROMA,PLSCAW(1,1,YDML_DYN%YYTLSCAW%M_WDLAT), A(1, :), B(2:YDML_DYN%NDIM, 1))
CALL LAITRI_WENO(YDDYN,NPROMA,PLSCAW(1,1,YDML_DYN%YYTLSCAW%M_WDLAT), YDML_DYN%ZTAB2(1, 2), B(1:4,1:3))
CALL LAITRI_WENO(YDDYN,NPROMA,PLSCAW(1,1,YDML_DYN%YYTLSCAW%M_WDLAT), YDML_DYN%ZTAB2(1, 2), B(1:4,:))
CALL LAITRI_WENO(YDDYN,NPROMA,PLSCAW(1,1,YDML_DYN%YYTLSCAW%M_WDLAT), YDML_DYN%ZTAB2(1, 2), B(1:4:2,:))
A(:,:) = 0.0
A(:,:) = B(:,:)+PECT(:,:) 
A(:,:)=B(:,:)
A(:,:)=B(:,:)-1
A=JOS(B)
YDMODEL%JJA(:,:)=YDMODEL%JJB(:,:)-1
YDMODEL%JJA(:,:)=YDMODEL%JJB(:,:)
A(KIDIA:KFIDIA,:)=B(KIDIA:KFIDIA,:)+3

DO JLEV=1,KLEV
DO JDLON=D%NIJB, D%NIJE
A(JDLON, JLEV)=C(JDLON,JLEV)+3
ENDDO
ENDDO

ZSUM = SUM (ZSURF (KIDIA:KFIDIA))
ZMIN = MINVAL (ZSURF (KIDIA:KFIDIA))
ZMAX = MAXVAL (ZSURF (KIDIA:KFIDIA))

Z1(KIDIA:KFIDIA)=Z2(KIDIA:KFIDIA)+3
DO JI_ = 1, KIT_
    GTRIG1_(JI_) = GTRIG1(ISORT(JI_))
    GTRIG2_(JI_) = YDVARS%GTRIG2(ISORT(JI_))
ENDDO

END SUBROUTINE
