SUBROUTINE SUB(YDML_DYN, A, B, D, YDML_DYN)
USE FIELD_ACCESS_MODULE

USE TYPE_MODEL         , ONLY : MODEL
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK

USE MY_MODULE, ONLY : MY_VAR
USE MY_MODULE, ONLY : MY_VAR_TYPE
USE MY_MODULE, ONLY : TMY_VAR
USE MY_MODULE, ONLY : MTYTYPE_VAR
#include "arp_shallow_mf.intfb.h"
IMPLICIT NONE 

TYPE(MODEL), INTENT(INOUT) :: YDMODEL

TYPE (DYN), INTENT(IN) :: YDML_DYN
REAL (KIND=JPRB) :: D(: ,:)
REAL (KIND=JPRB), INTENT(INOUT) :: A(YDMODEL%YRDIM%KLON, KLEV)

REAL (KIND=JPRB), INTENT(INOUT) :: B(: ,:)

REAL (KIND=JPRB), INTENT(OUT) :: PECT(KLON, KLEV) 
REAL (KIND=JPRB), INTENT(INOUT) :: PLSCAW(KLON, KLEV, XX)

!REAL (KIND=JPRB), POINTER :: ZR(KLON)
REAL (KIND=JPRB), ALLOCATABLE :: ZA(KLON)

REAL (KIND=JPRB) :: ZSURF(KLON)
REAL (KIND=JPRB) :: ZSUM(KLON)
REAL (KIND=JPRB) :: ZMIN(KLON)
REAL (KIND=JPRB) :: ZMAX(KLON)
REAL (KIND=JPRB) :: Z(KLON, KLEV) !allowed
REAL (KIND=JPRB) :: ZPROF (KLEV) !forbidden
REAL (KIND=JPRB) :: ZZ (4,2:5) !allowed 

REAL(KIND=JPRB), POINTER :: ZR(:,:)
REAL(KIND=JPRB), TARGET :: ZR0(KLON,KFLEVG)

!DO JLEV=0,KLEV
!DO JLON=KIDIA, KFDIA
!A(JLON, JLEV)=B(JLON, JLEV)
!ENDDO
!ENDDO

ZSUM = SUM (ZSURF (KIDIA:KFIDIA))
ZMIN = MINVAL (ZSURF (KIDIA:KFIDIA))
ZMAX = MAXVAL (ZSURF (KIDIA:KFIDIA))

END SUBROUTINE
