SUBROUTINE SUB(A, B, KLON, KLEV, YDVARS, PDELP)
USE FIELD_ACCESS_MODULE

USE TYPE_MODEL         , ONLY : MODEL
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK

USE MY_MODULE, ONLY : MY_VAR
USE MY_MODULE, ONLY : MY_VAR_TYPE
USE MY_MODULE, ONLY : TMY_VAR
USE MY_MODULE, ONLY : MTYTYPE_VAR
#include "arp_shallow_mf.intfb.h"
IMPLICIT NONE 

TYPE(MODEL), TARGET, INTENT(INOUT) :: YDVARS

REAL(KIND=JPRB)   ,INTENT(IN) :: A(:,:)
REAL(KIND=JPRB)   ,INTENT(IN) :: B(KLON, 0:KLEV)
REAL(KIND=JPRD),CONTIGUOUS,POINTER :: ZOPER(:,:)
REAL(KIND=JPRD),POINTER :: ZOPER(:,:)
REAL(KIND=JPRB) ,INTENT(OUT)   ,OPTIONAL ,TARGET  :: PDELP(KLON,KLEV) !,PLNPR(KPROMA,KFLEV),PRDELP(KPROMA,KFLEV),PALPH(KPROMA,KFLEV)

ZOPER => YDVFE%RINTGW(:,:)
ZDELP  => PDELP 
ZOPER(:,:)=0.0
CALL CALLEE(B)

END SUBROUTINE
