SUBROUTINE SUB(A, B, KLON, KLEV, YDVARS)
USE FIELD_ACCESS_MODULE

USE TYPE_MODEL         , ONLY : MODEL
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK

USE MY_MODULE, ONLY : MY_VAR
USE MY_MODULE, ONLY : MY_VAR_TYPE
USE MY_MODULE, ONLY : TMY_VAR
USE MY_MODULE, ONLY : MTYTYPE_VAR
#include "arp_shallow_mf.intfb.h"
IMPLICIT NONE 

TYPE(MODEL), INTENT(INOUT) :: YDVARS

REAL(KIND=JPRB)   ,INTENT(IN) :: A(:,:)
REAL(KIND=JPRB)   ,INTENT(IN) :: B(KLON, 0:KLEV)

DO JLON=1,KLON
DO JLEV=1,KLEV
A(JLON, JLEV)=B(JLON, JLEV)
ENDDO
ENDDO



END SUBROUTINE
