SUBROUTINE SUB1(A, B)

USE PARKIND1,ONLY:JPIM, JPRB, JLON, KLEV
IMPLICIT NONE 

REAL (KIND=JPRB), POINTER, INTENT(INOUT) :: A(KLON, KLEV)
REAL (KIND=JPRB), ALLOCATABLE, INTENT(INOUT) :: B(KLON)



END SUBROUTINE
