SUBROUTINE SUB5(A)
USE PARKIND1,ONLY:KLEV, TOTO
IMPLICIT NONE 
REAL (KIND=JPRB), INTENT(IN) :: A(:, :)
REAL (KIND=JPRB) :: B(:, :)
REAL (KIND=JPRB), POINTER :: C(:, :)
REAL (KIND=JPRB) :: C(TOTO)
REAL (KIND=JPRB) :: D(KLEV)
REAL (KIND=JPRB) :: E(5)


END SUBROUTINE
