SUBROUTINE SUB5(A)
USE PARKIND1,ONLY:KLEV
IMPLICIT NONE 
REAL (KIND=JPRB), INTENT(IN) :: A(:, :)
REAL (KIND=JPRB) :: B(:, :)
REAL (KIND=JPRB), POINTER :: C(:, :)
REAL (KIND=JPRB) :: D(KLEV)
REAL (KIND=JPRB) :: E(5)
REAL (KIND=JPRB) :: F(TOTO)


END SUBROUTINE
