SUBROUTINE GPHPRE_EXPL_VERTFE1 (KPROMA, KFLEV, KST, KEND, PRESF, LHSET, &
                              & LDELP, LALPHA, LRTGR, LRPP, PDELP, PLNPR, PRDELP, PALPH, PRTGR, PRPRE, PRPP)

USE PARKIND1,ONLY: JPIM, JPRB
USE YOMHOOK, ONLY: LHOOK, JPHOOK, DR_HOOK

USE YOMCST,    ONLY: TCST
USE YOMVERT,   ONLY: TVAB
USE YOMCVER,   ONLY: TCVER

IMPLICIT NONE

INTEGER(KIND=JPIM) ,INTENT(IN)                       :: KKKPROMA, KKPROMA, KPROMA,KFLEV,KST,KEND
REAL(KIND=JPRB)    ,INTENT(OUT)   ,OPTIONAL ,TARGET  :: PRESF(KKPROMA,KFLEV), APRESF(KPROMA, KFLEV), AZZPRESF(KPROMA, KFLEV)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL, TARGET :: BZZPRESF(KKPROMA, KFLEV), BPRESF(KKPROMA, KFLEV)
LOGICAL            ,INTENT(IN)    ,OPTIONAL          :: LHSET,LDELP,LALPHA,LRTGR,LRPP
REAL(KIND=JPRB)    ,INTENT(OUT)   ,OPTIONAL ,TARGET  :: PDELP(KPROMA,KFLEV),PLNPR(KPROMA,KFLEV),PRDELP(KPROMA,KFLEV),PALPH(KPROMA,KFLEV)
REAL(KIND=JPRB)    ,INTENT(OUT)   ,OPTIONAL ,TARGET  :: PRTGR(KPROMA,KFLEV),PRPRE(KPROMA,KFLEV),PRPP(KPROMA,KFLEV)

LOGICAL :: LLDELP, LLALPHA, LLRTGR, LLRPP, LTEST, LLXYB

REAL(KIND=JPRB),TARGET :: ZZPRESF(KKKPROMA,KFLEV), A2(KPROMA), A4(KFLEV)

REAL(KIND=JPRB),POINTER :: ZDELP (:,:), ZLNPR (:,:), ZRDELP (:,:), ZALPH (:,:), ZRTGR (:,:), ZRPRE (:,:), ZRPP (:,:), ZPRESF (:,:)
REAL(KIND=JPRB), POINTER :: A1(:), A3(:), AZPRESF(:, :), BZPRESF(:, :)
!LLXYB  = &
!& (PRESENT (PDELP) .AND.  PRESENT (PLNPR) .AND.  PRESENT (PRDELP) .AND.  PRESENT (PALPH) .AND. &
!&  PRESENT (PRTGR) .AND.  PRESENT (PRPRE) .AND.  PRESENT (PRPP))
LLXYB  = &
& (PRESENT (PDELP) .AND.  PRESENT (PRDELP) .AND.  PRESENT (PALPH) .AND. &
&  PRESENT (PRTGR) .AND.  PRESENT (PRPRE) .AND.  PRESENT (PRPP))
!PLNPR not in present

IF (LLXYB) THEN
  LLDELP = .TRUE.
  IF (PRESENT (LDELP)) LLDELP = LDELP
  LLALPHA = .TRUE.
  IF (PRESENT (LALPHA)) LLALPHA = LALPHA
  LLRTGR = .TRUE.
  IF (PRESENT (LRTGR)) LLRTGR = LRTGR

  ZDELP  => PDELP 
  ZLNPR  => PLNPR 
  ZRDELP => PRDELP
  ZALPH  => PALPH 
  ZRTGR  => PRTGR 
  ZRPRE  => PRPRE 
  ZRPP   => PRPP 
  ZLNPR  => PLNPR 

  IF (PRESENT(PRESF)) THEN
    ZPRESF => PRESF !KKPROMA
  ELSE
    ZPRESF => ZZPRESF !KKKPROMA
  ENDIF
ELSE
  NULLIFY (ZPRESF)
ENDIF

IF (PRESENT(PRESF)) THEN
  AZPRESF => APRESF !KPROMA
ELSE
  AZPRESF => AZZPRESF !KPROMA
ENDIF

IF (PRESENT(PRESF)) THEN
  BZPRESF => BPRESF !KKPROMA
ELSE
  BZPRESF => BZZPRESF !KKPROMA
ENDIF

A1 => A2
A3 => A4

END SUBROUTINE
